// Audit event constants for verification and profile changes
export const AUDIT_EVENTS = {
  PROFILE_CREATED: "PROFILE_CREATED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  GPS_CAPTURED: "GPS_CAPTURED",
  OTP_VERIFIED: "OTP_VERIFIED",
  NIDA_VERIFIED: "NIDA_VERIFIED",
  APPLICATION_BLOCKED_PROFILE: "APPLICATION_BLOCKED_PROFILE",
  VERIFICATION_LEVEL_CHANGED: "VERIFICATION_LEVEL_CHANGED",
} as const;

export type AuditEventKey = keyof typeof AUDIT_EVENTS;

export default AUDIT_EVENTS;
