/**
 * Shared types, styles and helpers for all E-Mtaa PDF documents.
 * Layout follows Tanzanian local government document conventions:
 *   - Coat of Arms centred at top
 *   - "JAMHURI YA MUUNGANO WA TANZANIA" heading
 *   - Photo box top-left, QR code bottom-right
 *   - Application number as prominent serial ID
 *   - Dual-language (Swahili primary, English secondary)
 */
import { StyleSheet } from "@react-pdf/renderer";
import { Application } from "@/lib/supabase";
import type { UserProfile } from "@/lib/supabase";

export interface DocumentPDFProps {
  application: Application;
  lang: "sw" | "en";
  qrDataUrl?: string; // pre-generated by useQRCode hook; falls back to API URL
  /** Citizen profile photo (base64/data URL) — embedded on certificates/letters */
  photoUrl?: string | null;
}

// ─── Colour tokens ─────────────────────────────────────────────────────────────
const C = {
  ink: "#111111",
  inkLight: "#3a3a3a",
  inkFaint: "#6b6b6b",
  rule: "#c0c0c0",
  ruleLight: "#e8e8e8",
  emerald: "#1a5632", // Government green — used sparingly
  emeraldMid: "#1a5632",
  emeraldBg: "#f7f7f7", // Very subtle grey, not green
  gold: "#6b4c1e",
  goldBg: "#faf8f5",
  white: "#ffffff",
  pageBg: "#ffffff", // Clean white — prints perfectly
};

// ─── Shared stylesheet ─────────────────────────────────────────────────────────
export const commonStyles = StyleSheet.create({
  // Page
  page: {
    paddingTop: 24,
    paddingBottom: 28,
    paddingHorizontal: 36,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: C.ink,
    backgroundColor: C.white,
  },

  // ── Watermark ──────────────────────────────────────────────────────────────
  watermark: {
    position: "absolute",
    top: "40%",
    left: "18%",
    fontSize: 80,
    color: "#eeeeee",
    opacity: 0.35,
    transform: "rotate(-40deg)",
    letterSpacing: 8,
  },

  // ── Photo box (top-left absolute) ─────────────────────────────────────────
  photoSection: {
    position: "absolute",
    top: 36,
    left: 44,
    width: 76,
    alignItems: "center",
  },
  photoBox: {
    width: 68,
    height: 82,
    borderWidth: 1.5,
    borderColor: C.inkFaint,
    backgroundColor: C.ruleLight,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 3,
  },
  photo: {
    width: 66,
    height: 80,
    objectFit: "cover",
  },
  photoPlaceholder: {
    fontSize: 7,
    color: C.inkFaint,
    textAlign: "center",
    lineHeight: 1.4,
  },
  nidaLabel: {
    fontSize: 5.5,
    color: C.inkFaint,
    marginBottom: 1,
    textAlign: "center",
  },
  nidaNumber: {
    fontSize: 6.5,
    fontWeight: "bold",
    color: C.ink,
    textAlign: "center",
    fontFamily: "Courier",
  },

  // ── Government header (centred) ────────────────────────────────────────────
  header: {
    alignItems: "center",
    marginBottom: 6,
    paddingLeft: 80, // clear the photo box
  },
  logo: {
    width: 54,
    height: 54,
    marginBottom: 6,
    backgroundColor: "#ffffff",
  },
  country: {
    fontSize: 11,
    fontWeight: "bold",
    letterSpacing: 0.5,
    textAlign: "center",
    marginBottom: 1,
  },
  office: {
    fontSize: 9,
    fontWeight: "bold",
    color: C.inkLight,
    textAlign: "center",
    marginBottom: 2,
  },
  council: {
    fontSize: 8.5,
    color: C.inkLight,
    textAlign: "center",
    marginBottom: 6,
  },
  divider: {
    width: 48,
    height: 1,
    backgroundColor: C.ink,
    marginTop: 4,
  },

  // ── Document title ─────────────────────────────────────────────────────────
  titleBlock: {
    marginTop: 6,
    marginBottom: 2,
    alignItems: "center",
  },
  title: {
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    textTransform: "uppercase",
    color: C.ink,
    letterSpacing: 1.5,
  },
  appNumberBadge: {
    marginTop: 5,
    borderWidth: 1,
    borderColor: C.rule,
    paddingVertical: 3,
    paddingHorizontal: 14,
    alignSelf: "center",
  },
  appNumberText: {
    color: C.inkLight,
    fontSize: 8.5,
    fontFamily: "Courier",
    fontWeight: "bold",
    letterSpacing: 1,
  },

  // ── Section headers ────────────────────────────────────────────────────────
  sectionHeader: {
    paddingBottom: 3,
    marginBottom: 4,
    marginTop: 6,
    borderBottomWidth: 0.75,
    borderBottomColor: C.ink,
    flexDirection: "row",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 8,
    fontWeight: "bold",
    color: C.ink,
    textTransform: "uppercase",
    letterSpacing: 1,
  },

  // ── Info rows ──────────────────────────────────────────────────────────────
  infoRow: {
    flexDirection: "row",
    marginBottom: 2.5,
    paddingBottom: 2,
    borderBottomWidth: 0.3,
    borderBottomColor: C.ruleLight,
    minHeight: 12,
  },
  infoLabel: {
    width: "36%",
    fontSize: 8.5,
    color: C.inkFaint,
    paddingRight: 6,
  },
  infoValue: {
    width: "64%",
    fontSize: 9,
    color: C.ink,
    fontWeight: "bold",
  },

  // ── Two-column layout ──────────────────────────────────────────────────────
  twoCol: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  colLeft: { width: "48%" },
  colRight: { width: "48%" },

  // ── Signature section ──────────────────────────────────────────────────────
  signatureSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 6,
  },
  signatureBox: {
    width: "44%",
    alignItems: "center",
  },
  signatureLine: {
    borderBottomWidth: 1,
    borderBottomColor: C.inkFaint,
    marginBottom: 6,
    width: "100%",
  },
  signatureImg: {
    width: 90,
    height: 36,
    objectFit: "contain",
    marginBottom: 2,
  },
  stampImg: {
    width: 60,
    height: 60,
    objectFit: "contain",
    marginBottom: 4,
  },
  signatureName: {
    fontSize: 9,
    fontWeight: "bold",
    textTransform: "uppercase",
    textAlign: "center",
    marginBottom: 2,
  },
  signatureTitle: {
    fontSize: 8,
    color: C.inkFaint,
    textAlign: "center",
  },
  stampBox: {
    width: 58,
    height: 58,
    borderWidth: 1,
    borderColor: C.ruleLight,
    borderStyle: "dashed",
    borderRadius: 29,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
  },
  stampText: {
    fontSize: 5.5,
    color: C.ruleLight,
    textAlign: "center",
  },

  // ── QR code block (inline, right-aligned, after signatures) ──────────────
  qrSection: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 4,
    marginBottom: 0,
  },
  qrInner: {
    alignItems: "center",
    width: 76,
  },
  qrBorder: {
    borderWidth: 1,
    borderColor: C.rule,
    padding: 3,
    backgroundColor: C.white,
    marginBottom: 3,
  },
  qrCode: {
    width: 52,
    height: 52,
  },
  qrLabel: {
    fontSize: 5.5,
    color: C.inkFaint,
    textAlign: "center",
    lineHeight: 1.4,
  },
  qrRef: {
    fontSize: 5,
    color: C.inkFaint,
    textAlign: "center",
    fontFamily: "Courier",
    marginTop: 1,
  },

  // ── Footer ─────────────────────────────────────────────────────────────────
  footer: {
    marginTop: 12,
    borderTopWidth: 0.5,
    borderTopColor: C.rule,
    paddingTop: 5,
    flexDirection: "column",
    alignItems: "center",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  disclaimer: {
    fontSize: 6,
    color: "#999999",
    textAlign: "center",
    fontWeight: "bold",
    marginBottom: 3,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  footerText: {
    fontSize: 7,
    color: C.inkFaint,
    fontStyle: "italic",
    flex: 1,
  },
  metadata: {
    fontSize: 5.5,
    color: C.rule,
    fontFamily: "Courier",
    textAlign: "right",
  },

  // ── Notice / info box ──────────────────────────────────────────────────────
  noticeBox: {
    backgroundColor: C.emeraldBg,
    borderWidth: 0.5,
    borderColor: C.rule,
    padding: 5,
    marginVertical: 5,
  },
  noticeText: {
    fontSize: 7.5,
    color: C.inkLight,
    lineHeight: 1.35,
  },

  // ── Subject line (for letter-format docs) ─────────────────────────────────
  subject: {
    fontSize: 10,
    fontWeight: "bold",
    marginBottom: 10,
    textDecoration: "underline",
  },
  body: {
    fontSize: 9.5,
    lineHeight: 1.7,
    textAlign: "justify",
    marginBottom: 14,
    color: C.ink,
  },
});

// ─── Helpers ───────────────────────────────────────────────────────────────────

/** Generate the QR code image URL (external API fallback used by default).
 *  For async pre-generation use generateQRDataUrl from src/lib/qr.ts.
 */
export const generateQRCodeUrl = (application: Application, serviceCode: string): string => {
  const payload = JSON.stringify({
    ref: application.application_number ?? "",
    id: application.id,
    svc: serviceCode,
    dt: new Date().toISOString().split("T")[0],
  });
  return `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(payload)}`;
};

export const formatFullName = (
  user: Partial<Pick<UserProfile, "first_name" | "middle_name" | "last_name">> | null | undefined,
): string => {
  if (!user) return "N/A";
  return (
    `${user.first_name ?? ""} ${user.middle_name ?? ""} ${user.last_name ?? ""}`
      .replace(/\s+/g, " ")
      .trim() || "N/A"
  );
};

export const formatDate = (dateString?: string | null): string => {
  if (!dateString) return new Date().toLocaleDateString("sw-TZ");
  try {
    return new Date(dateString).toLocaleDateString("sw-TZ");
  } catch {
    return dateString;
  }
};

export const formatCurrency = (amount?: number | null): string => {
  if (!amount && amount !== 0) return "N/A";
  return `TZS ${Number(amount).toLocaleString("en-TZ")}`;
};

/** Shared government header used by every document type. */
export { commonStyles as default };
